name: AgriDeco
version: '1.0'
main: me.sunmc.ad.AgriDeco
api-version: '1.21.4'
folia-supported: true

libraries:
  - com.zaxxer:HikariCP:7.0.2
  - mysql:mysql-connector-java:9.6.0
  - com.fasterxml.jackson.core:jackson-databind:3.1.0

authors: [ SunMC ]
softdepend: [ AuraSkills, Jobs, GriefPrevention ]
depend: [ packetevents, MMOItems ]

commands:
  agrideco:
    description: "AgriDeco main command."
    aliases: [ deco, agri ]
    usage: "/<command> <reload|give|gui>"
    permission: agrideco.use

permissions:
  agrideco.use:
    default: true
  agrideco.admin:
    default: op